// Panoptic - Registre canonique des agents d'audit.
// Chaque agent est autonome, recoit un perimetre du scoping, produit des findings
// au format unique defini dans schema.js, puis passe par la verification adversariale.
// family: technique | visibilite | humain | risque
// activation: "always" | condition (evaluee sur le contexte de scoping)

export const AGENTS = [
  {
    id: "security",
    n: 1,
    family: "technique",
    name: "Securite applicative",
    mission: "Trouver les vulnerabilites exploitables, cote code et cote prod.",
    frameworks: ["OWASP Top 10 (2021)", "OWASP ASVS", "CWE Top 25"],
    checks: [
      "Injections SQL / NoSQL / command", "XSS", "CSRF", "SSRF",
      "IDOR / controle d'acces casse", "Deserialisation non securisee",
      "Authentification et gestion de session", "Gestion des secrets",
      "Upload de fichiers", "En-tetes de securite (CSP, HSTS, X-Frame-Options)",
      "Rate limiting", "Exposition d'endpoints sensibles",
    ],
    tools: ["semgrep", "codeql", "owasp-zap", "nuclei", "gitleaks", "trufflehog", "testssl.sh"],
    inputs: {
      code: "Analyse statique du repo, patterns dangereux, secrets committes.",
      prod: "Requetes actives non destructives, headers reels, endpoints exposes.",
    },
    scoring: "CVSS 3.1",
    weight: 1.0,
    activation: "always",
  },
  {
    id: "code-arch",
    n: 2,
    family: "technique",
    name: "Code et architecture",
    mission: "Qualite, maintenabilite, dette technique, coherence architecturale.",
    frameworks: ["SOLID", "Clean Architecture", "DDD", "Metriques de complexite"],
    checks: [
      "Complexite cyclomatique", "Duplication de code", "Couplage / cohesion",
      "Couverture de tests", "Code mort", "Anti-patterns",
      "Respect des couches", "Gestion d'erreurs", "TODO / FIXME critiques",
    ],
    tools: ["sonarqube", "eslint", "coverage", "jscpd"],
    inputs: {
      code: "Lecture du repo, arbre de dependances internes, tests.",
      prod: "Coherence code / comportement observe (routes mortes, features desactivees).",
    },
    scoring: "Dette en jours-homme",
    weight: 0.7,
    activation: "hasRepo",
  },
  {
    id: "infra",
    n: 3,
    family: "technique",
    name: "Infrastructure / DevOps / hebergement",
    mission: "Robustesse de tout ce qui n'est pas le code applicatif.",
    frameworks: ["Well-Architected", "12-Factor App"],
    checks: [
      "DNS", "TLS / certificats (expiration, chaine)", "CDN et cache",
      "Headers serveur", "CI/CD (secrets pipeline, etapes securite)", "IaC",
      "Sauvegardes + restauration testee", "Monitoring / alerting",
      "Uptime et redondance", "Scalabilite", "Couts",
    ],
    tools: ["dig", "testssl.sh", "tfsec", "checkov", "trivy"],
    inputs: {
      code: "Dockerfiles, config CI/CD, IaC, .env exposes.",
      prod: "Reponse serveur reelle, certs live, temps de reponse, disponibilite.",
    },
    scoring: "Risque infra (impact x probabilite)",
    weight: 0.9,
    activation: "always",
  },
  {
    id: "data",
    n: 4,
    family: "technique",
    name: "Donnees et base de donnees",
    mission: "Sante, integrite et securite de la donnee.",
    frameworks: ["Normalisation", "Bonnes pratiques d'indexation", "Principes de retention"],
    checks: [
      "Schema", "Index manquants / inutiles", "Requetes N+1", "Requetes lentes",
      "Integrite referentielle", "Volumetrie", "Politique de retention",
      "Chiffrement au repos", "PII exposees", "Migrations",
    ],
    tools: ["explain-analyzer", "sqlfluff", "schema-inspector"],
    inputs: {
      code: "ORM, migrations, requetes dans le repo.",
      prod: "Plans d'execution reels, index existants, tailles de tables.",
    },
    scoring: "Gain de perf estime + risque PII",
    weight: 0.8,
    activation: "hasDatabase",
  },
  {
    id: "deps",
    n: 5,
    family: "technique",
    name: "Dependances / supply chain / licences",
    mission: "Le risque qui vient de ce que vous n'avez pas ecrit.",
    frameworks: ["OWASP Dependency-Check", "SLSA", "SPDX"],
    checks: [
      "CVE connues", "Versions obsoletes", "Packages abandonnes",
      "Dependances transitives", "Typosquatting",
      "Compatibilite des licences (GPL dans proprio)", "Integrite du lockfile",
    ],
    tools: ["snyk", "osv-scanner", "npm-audit", "pip-audit", "license-checker"],
    inputs: {
      code: "package.json / lockfiles, imports reels vs declares.",
      prod: "Versions effectivement servies (JS front, headers de version).",
    },
    scoring: "CVSS + criticite licence",
    weight: 0.85,
    activation: "always",
  },
  {
    id: "perf",
    n: 6,
    family: "technique",
    name: "Performance / Core Web Vitals",
    mission: "Vitesse ressentie et technique, terrain et labo.",
    frameworks: ["Core Web Vitals (LCP, INP, CLS)", "RAIL", "Budgets de perf"],
    checks: [
      "LCP", "INP", "CLS", "Poids des pages", "Images non optimisees",
      "JS bloquant / render-blocking", "Lazy loading", "TTFB",
      "Cache et compression", "Waterfall reseau",
    ],
    tools: ["lighthouse", "webpagetest", "crux", "bundle-analyzer"],
    inputs: {
      code: "Bundles, imports lourds, config build, images sources.",
      prod: "Mesures reelles labo + terrain CrUX, waterfall.",
    },
    scoring: "Score CWV + gain en ms",
    weight: 0.9,
    activation: "always",
  },
  {
    id: "seo",
    n: 7,
    family: "visibilite",
    name: "SEO technique",
    mission: "Indexabilite et sante technique pour le referencement.",
    frameworks: ["Google Search Essentials", "Standards techniques SEO"],
    checks: [
      "Crawlabilite (robots.txt, sitemap)", "Indexabilite (noindex, canonicals)",
      "Structure des URLs", "Balises meta", "Donnees structurees (Schema.org)",
      "hreflang", "Maillage interne", "Redirections / 404",
      "Mobile-first", "Rendu JS",
    ],
    tools: ["screaming-frog-core", "schema-validator", "rich-results-test", "gsc"],
    inputs: {
      code: "Templates, generation des metas, SSR/SSG, i18n routing.",
      prod: "HTML rendu reel, statuts HTTP, sitemap live.",
    },
    scoring: "Erreurs bloquantes + opportunites",
    weight: 0.85,
    activation: "always",
  },
  {
    id: "geo",
    n: 8,
    family: "visibilite",
    name: "GEO (visibilite IA)",
    mission: "Etre cite par les moteurs de reponse IA, pas seulement Google.",
    frameworks: ["Bonnes pratiques GEO", "llms.txt"],
    checks: [
      "Accessibilite aux crawlers IA", "Presence / qualite de llms.txt",
      "Citabilite au niveau paragraphe", "Signaux E-E-A-T",
      "Structure question / reponse", "Mentions de marque",
      "Donnees factuelles extractibles",
    ],
    tools: ["ai-citation-tester", "content-structure-analyzer", "llms-txt-check"],
    inputs: {
      code: "Structure du contenu, donnees structurees, presence llms.txt.",
      prod: "Ce que voient reellement les bots IA, citations effectives.",
    },
    scoring: "Score de citabilite",
    weight: 0.6,
    activation: "always",
  },
  {
    id: "analytics",
    n: 9,
    family: "visibilite",
    name: "Analytics et mesure",
    mission: "Garantir que les donnees de decision sont justes.",
    frameworks: ["Plan de tracking", "GA4", "Consent Mode v2"],
    checks: [
      "Presence et integrite du tracking", "Events casses", "Double comptage",
      "Coherence du dataLayer", "Consent Mode", "Attribution",
      "Conformite du tracking au consentement", "Tag manager propre",
    ],
    tools: ["tag-inspector", "datalayer-validator", "ga4-debugger"],
    inputs: {
      code: "Implementation des events, dataLayer, config GTM.",
      prod: "Tags qui se declenchent reellement, requetes analytics observees.",
    },
    scoring: "Events defectueux + ecart de mesure",
    weight: 0.6,
    activation: "always",
  },
  {
    id: "email",
    n: 10,
    family: "visibilite",
    name: "Email et delivrabilite",
    mission: "Que les emails arrivent et ne soient pas usurpes.",
    frameworks: ["SPF", "DKIM", "DMARC", "BIMI"],
    checks: [
      "SPF / DKIM / DMARC (presence, syntaxe, politique)", "Alignement",
      "Reputation IP / domaine", "Qualite des templates (poids, spam score)",
      "Liens de desinscription", "Blocklists",
    ],
    tools: ["dns-mail-check", "spf-dkim-dmarc-tester", "spam-scorer"],
    inputs: {
      code: "Templates d'email, config d'envoi, adresses d'expedition.",
      prod: "Enregistrements DNS live, headers d'emails reels.",
    },
    scoring: "Failles d'usurpation + score de delivrabilite",
    weight: 0.5,
    // Toujours actif: l'anti-usurpation (SPF/DMARC) protege le domaine meme sans envoi.
    activation: "always",
  },
  {
    id: "a11y",
    n: 11,
    family: "humain",
    name: "Accessibilite (WCAG)",
    mission: "Rendre le site utilisable par tous, et conforme legalement.",
    frameworks: ["WCAG 2.2 AA", "RGAA", "European Accessibility Act (juin 2025)"],
    checks: [
      "Contrastes", "Alternatives textuelles", "Navigation clavier",
      "Focus visible", "ARIA correct", "Structure des titres",
      "Labels de formulaires", "Compatibilite lecteurs d'ecran",
      "Cibles tactiles", "Sous-titres media",
    ],
    tools: ["axe-core", "lighthouse-a11y", "contrast-checker"],
    inputs: {
      code: "Composants, ARIA, semantique HTML, ordre de tab.",
      prod: "Rendu reel, comportement clavier / focus live.",
    },
    scoring: "Non-conformites WCAG + risque legal",
    weight: 0.9,
    activation: "always",
  },
  {
    id: "ux",
    n: 12,
    family: "humain",
    name: "UX / UI / parcours",
    mission: "Ergonomie et coherence de l'experience (distinct du CRO).",
    frameworks: ["Heuristiques de Nielsen", "Lois UX (Fitts, Hick)", "Design system"],
    checks: [
      "Parcours utilisateurs", "Coherence visuelle (espacements, typo, couleurs)",
      "Etats (chargement, vide, erreur)", "Responsive / mobile",
      "Frictions hors funnel", "Feedback d'interaction",
      "Hierarchie visuelle", "Formulaires",
    ],
    tools: ["heuristic-audit", "multi-breakpoint-capture", "design-system-analyzer"],
    inputs: {
      code: "Composants UI, tokens de design, gestion des etats.",
      prod: "Rendu reel desktop / tablette / mobile, parcours cliquables.",
    },
    scoring: "Frictions par parcours",
    weight: 0.7,
    activation: "always",
  },
  {
    id: "content",
    n: 13,
    family: "humain",
    name: "Contenu / editorial / i18n",
    mission: "Qualite du contenu et integrite multilingue.",
    frameworks: ["Bonnes pratiques editoriales", "Coherence de ton", "Standards i18n/l10n"],
    checks: [
      "Orthographe / grammaire", "Ton et coherence de marque",
      "Fraicheur (dates, stats perimees)", "Traductions manquantes / cassees",
      "Cles i18n non resolues", "Formats locaux (dates, devises)",
      "Lisibilite", "Doublons de contenu",
    ],
    tools: ["spell-grammar", "i18n-diff", "readability-analyzer"],
    inputs: {
      code: "Fichiers de traduction, cles i18n, contenu en dur.",
      prod: "Texte rendu reel dans chaque langue.",
    },
    scoring: "Erreurs editoriales + trous de traduction",
    weight: 0.6,
    activation: "always",
  },
  {
    id: "legal",
    n: 14,
    family: "risque",
    name: "Juridique / RGPD",
    mission: "Le poste ou le client risque une amende. Framework dedie.",
    frameworks: ["RGPD", "ePrivacy", "DSA", "RGAA / EAA 2025"],
    checks: [
      "Bandeau cookies et consentement reel (pas cosmetique)", "Mentions legales",
      "CGV / CGU", "Registre des traitements", "Transferts hors UE",
      "Politique de confidentialite", "DPO", "Duree de conservation",
    ],
    tools: ["cookie-scanner", "consent-flow-tester", "legal-doc-check"],
    inputs: {
      code: "Gestion du consentement, chargement conditionnel des tags.",
      prod: "Comportement reel du bandeau, cookies deposes avant consentement.",
    },
    scoring: "Risque d'amende (severite reglementaire)",
    weight: 0.95,
    activation: "always",
  },
  {
    id: "cro",
    n: 15,
    family: "risque",
    name: "CRO / conversion",
    mission: "Optimiser la transformation (distinct de l'UX qui audite l'ergonomie).",
    frameworks: ["Principes de persuasion", "Optimisation de funnel", "A/B testing"],
    checks: [
      "Clarte de la proposition de valeur", "CTA (visibilite, formulation)",
      "Longueur / friction des formulaires", "Preuve sociale",
      "Hierarchie de conversion", "Funnel d'achat", "Abandons",
      "Urgence / rarete",
    ],
    tools: ["funnel-analyzer", "cta-audit", "form-friction-scorer"],
    inputs: {
      code: "Composants de conversion, formulaires, tunnels.",
      prod: "Parcours d'achat reel, points d'abandon observes.",
    },
    scoring: "Fuites de conversion + gain estime",
    weight: 0.7,
    activation: "always",
  },
];

export const FAMILIES = {
  technique: { label: "Technique", agents: ["security", "code-arch", "infra", "data", "deps", "perf"] },
  visibilite: { label: "Visibilite", agents: ["seo", "geo", "analytics", "email"] },
  humain: { label: "Humain", agents: ["a11y", "ux", "content"] },
  risque: { label: "Risque", agents: ["legal", "cro"] },
};

// Evalue quels agents s'activent selon le contexte de scoping.
export function activeAgents(scope) {
  const cond = {
    always: () => true,
    hasRepo: () => Boolean(scope.repo),
    hasDatabase: () => Boolean(scope.database),
    sendsEmail: () => Boolean(scope.sendsEmail),
  };
  return AGENTS.filter((a) => (cond[a.activation] || cond.always)());
}
