// Panoptic - Agent securite: referentiel de regles statiques (SAST + secrets).
// Approche semgrep/gitleaks-lite: regex par ligne, mapping CWE, sans dependance.
// Chaque regle: id, cwe, severity, title, fix, effort (jours-homme), et soit `re` (regex),
// soit `test(line)` pour la logique fine. `confidence` module la verification adversariale.

// --- Detection de secrets committes -------------------------------------------------
export const SECRET_RULES = [
  { id: "stripe-secret-live", cwe: "CWE-798", severity: "critical", effort: 0.5, confidence: "high",
    title: "Cle secrete Stripe live exposee", re: /\bsk_live_[0-9a-zA-Z]{20,}/,
    fix: "Revoquer la cle dans Stripe, la deplacer cote serveur en variable d'env, purger l'historique git." },
  { id: "stripe-restricted-live", cwe: "CWE-798", severity: "critical", effort: 0.5, confidence: "high",
    title: "Cle restreinte Stripe live exposee", re: /\brk_live_[0-9a-zA-Z]{20,}/,
    fix: "Revoquer et regenerer la cle, la sortir du code source." },
  { id: "aws-access-key", cwe: "CWE-798", severity: "critical", effort: 0.5, confidence: "high",
    title: "AWS Access Key ID exposee", re: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/,
    fix: "Desactiver la cle dans IAM, en creer une nouvelle, utiliser un secret manager." },
  { id: "google-api-key", cwe: "CWE-798", severity: "high", effort: 0.4, confidence: "high",
    title: "Cle API Google exposee", re: /\bAIza[0-9A-Za-z\-_]{35}\b/,
    fix: "Restreindre puis regenerer la cle dans la console Google Cloud." },
  { id: "github-token", cwe: "CWE-798", severity: "critical", effort: 0.4, confidence: "high",
    title: "Token GitHub expose", re: /\b(?:ghp|gho|ghu|ghs|ghr)_[0-9A-Za-z]{36}\b|\bgithub_pat_[0-9A-Za-z_]{22,}/,
    fix: "Revoquer le token dans les parametres GitHub, purger l'historique." },
  { id: "slack-token", cwe: "CWE-798", severity: "high", effort: 0.4, confidence: "high",
    title: "Token Slack expose", re: /\bxox[baprs]-[0-9A-Za-z-]{10,}/,
    fix: "Revoquer le token dans l'admin Slack." },
  { id: "sendgrid-key", cwe: "CWE-798", severity: "high", effort: 0.4, confidence: "high",
    title: "Cle API SendGrid exposee", re: /\bSG\.[0-9A-Za-z_-]{22}\.[0-9A-Za-z_-]{43}\b/,
    fix: "Supprimer la cle dans SendGrid, en creer une nouvelle." },
  { id: "openai-key", cwe: "CWE-798", severity: "high", effort: 0.4, confidence: "high",
    title: "Cle API OpenAI exposee", re: /\bsk-(?:proj-)?[0-9A-Za-z_-]{20,}/,
    fix: "Revoquer la cle sur platform.openai.com, la sortir du bundle." },
  { id: "private-key", cwe: "CWE-798", severity: "critical", effort: 0.6, confidence: "high",
    title: "Cle privee cryptographique dans le code", re: /-----BEGIN (?:RSA |EC |OPENSSH |DSA |PGP )?PRIVATE KEY-----/,
    fix: "Retirer la cle du depot, la revoquer, la stocker dans un coffre." },
  { id: "jwt-hardcoded", cwe: "CWE-798", severity: "medium", effort: 0.3, confidence: "medium",
    title: "JWT en dur dans le code", re: /\beyJ[0-9A-Za-z_-]{10,}\.eyJ[0-9A-Za-z_-]{10,}\.[0-9A-Za-z_-]{10,}/,
    fix: "Ne jamais committer de JWT; le generer a la demande." },
  { id: "generic-secret-assign", cwe: "CWE-798", severity: "medium", effort: 0.3, confidence: "low",
    title: "Secret probable assigne en dur",
    re: /\b(?:api[_-]?key|secret|token|passwd|password|client[_-]?secret|auth[_-]?token)\b\s*[:=]\s*['"][^'"\s]{16,}['"]/i,
    fix: "Deplacer la valeur en variable d'environnement." },
];

// --- Sinks et anti-patterns dangereux (SAST) ---------------------------------------
export const CODE_RULES = [
  { id: "js-eval", cwe: "CWE-95", severity: "high", effort: 0.4, confidence: "medium", langs: ["js", "ts"],
    title: "Execution dynamique de code (eval / new Function)",
    re: /\beval\s*\(|new\s+Function\s*\(/,
    fix: "Supprimer eval; utiliser un parseur explicite ou une table de dispatch." },
  { id: "js-inner-html", cwe: "CWE-79", severity: "high", effort: 0.3, confidence: "medium", langs: ["js", "ts", "html"],
    title: "Injection DOM via innerHTML avec une variable (XSS)",
    re: /\.(?:inner|outer)HTML\s*(?:\+?=)\s*(?![`'"])[A-Za-z_$]/,
    fix: "Utiliser textContent, ou assainir avec DOMPurify avant l'injection." },
  { id: "react-dangerous-html", cwe: "CWE-79", severity: "high", effort: 0.3, confidence: "medium", langs: ["jsx", "tsx", "js", "ts"],
    title: "dangerouslySetInnerHTML sur une valeur dynamique (XSS)",
    re: /dangerouslySetInnerHTML\s*=\s*\{\{[^}]*\b(?!__html\s*:\s*['"`])/,
    fix: "Assainir le HTML avec DOMPurify, ou rendre du texte." },
  { id: "js-document-write", cwe: "CWE-79", severity: "medium", effort: 0.3, confidence: "medium", langs: ["js", "ts", "html"],
    title: "document.write (XSS et blocage de rendu)", // panoptic-ignore (auto-reference de la regle)
    re: /document\.write(?:ln)?\s*\(/,
    fix: "Remplacer par une manipulation DOM sure." },
  { id: "cmd-injection", cwe: "CWE-78", severity: "critical", effort: 0.5, confidence: "medium", langs: ["js", "ts"],
    title: "Injection de commande via child_process avec interpolation",
    re: /\b(?:exec|execSync|spawn|spawnSync)\s*\(\s*[`'"][^`'"]*\$\{|\b(?:exec|execSync)\s*\([^)]*\+/,
    fix: "Utiliser execFile avec un tableau d'arguments; jamais de shell interpole." },
  { id: "sql-injection", cwe: "CWE-89", severity: "critical", effort: 0.5, confidence: "medium", langs: ["js", "ts", "py", "php"],
    title: "Requete SQL construite par concatenation (injection)",
    re: /(?:SELECT|INSERT|UPDATE|DELETE|WHERE|FROM)\b[^;`'"]*(?:`[^`]*\$\{|['"]\s*\+\s*[A-Za-z_$])/i,
    fix: "Utiliser des requetes parametrees / preparees." },
  { id: "weak-hash", cwe: "CWE-327", severity: "medium", effort: 0.3, confidence: "high", langs: ["js", "ts", "py"],
    title: "Algorithme de hachage faible (MD5 / SHA-1)",
    re: /createHash\s*\(\s*['"](?:md5|sha1)['"]|hashlib\.(?:md5|sha1)\s*\(/i,
    fix: "Utiliser SHA-256 minimum; bcrypt / argon2 pour les mots de passe." },
  { id: "weak-cipher", cwe: "CWE-327", severity: "high", effort: 0.4, confidence: "high", langs: ["js", "ts"],
    title: "Chiffrement obsolete (createCipher sans IV)",
    re: /\bcreateCipher\s*\(|\bcreateDecipher\s*\(/,
    fix: "Utiliser createCipheriv avec un IV aleatoire (AES-256-GCM)." },
  { id: "tls-disabled", cwe: "CWE-295", severity: "high", effort: 0.2, confidence: "high", langs: ["js", "ts"],
    title: "Verification TLS desactivee",
    re: /rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0/,
    fix: "Retablir la verification du certificat; corriger la chaine de confiance." },
  { id: "cors-wildcard", cwe: "CWE-942", severity: "medium", effort: 0.2, confidence: "high", langs: ["js", "ts"],
    title: "CORS permissif (Access-Control-Allow-Origin: *)",
    re: /Access-Control-Allow-Origin['"]?\s*[:,]\s*['"]\*['"]/,
    fix: "Restreindre l'origine a une liste blanche." },
  { id: "insecure-random", cwe: "CWE-338", severity: "medium", effort: 0.3, confidence: "low", langs: ["js", "ts"],
    title: "Math.random() pour une valeur sensible (token / secret)",
    re: /\b(?:token|secret|nonce|otp|password|salt|apikey|api_key)\b[^;\n]*Math\.random\s*\(/i,
    fix: "Utiliser crypto.randomBytes / crypto.getRandomValues." },
  { id: "cleartext-http", cwe: "CWE-319", severity: "medium", effort: 0.2, confidence: "low", langs: ["js", "ts", "py", "php", "env"],
    title: "Endpoint d'API en HTTP clair",
    re: /['"]http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0)[^'"\s]+(?:api|auth|login|token|pay)[^'"\s]*/i,
    fix: "Forcer HTTPS pour tout endpoint d'authentification ou d'API." },
  { id: "py-insecure-deser", cwe: "CWE-502", severity: "high", effort: 0.4, confidence: "medium", langs: ["py"],
    title: "Deserialisation non securisee (pickle / yaml.load)",
    re: /\bpickle\.loads?\s*\(|\byaml\.load\s*\((?![^)]*Loader\s*=\s*yaml\.SafeLoader)/,
    fix: "Utiliser json, ou yaml.safe_load; jamais pickle sur des donnees externes." },
  { id: "py-shell-true", cwe: "CWE-78", severity: "high", effort: 0.4, confidence: "medium", langs: ["py"],
    title: "subprocess avec shell=True (injection de commande)",
    re: /subprocess\.(?:call|run|Popen|check_output)\s*\([^)]*shell\s*=\s*True|\bos\.system\s*\(/,
    fix: "Passer une liste d'arguments et shell=False; valider les entrees." },
];
